version: '3.8'

services:
  logipservice:
    build:       
      context: .
      dockerfile: ./LogIPServiceTestAssignment/Dockerfile
    ports:
      - "50051:50051"
    depends_on:
      - postgres
      - kafka
      - k6-load-test
    environment:
      - ConnectionStrings__LogIPDB=Host=postgres;Database=logsdb;Username=postgres;Password=postgres
      - Kafka__BootstrapServers=kafka:9092
#Databases
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - ./runtime/db:/var/lib/postgresql/data
#Brokers
  kafka:
    image: bitnami/kafka:3.4
    container_name: kafka
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  # Zookeeper (required for Kafka)
  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
  
  #Load Tests
  k6-load-test:
    build:
      context: .
      dockerfile: k6-tests/Dockerfile
    volumes:
      - ./k6-tests:/scripts
    depends_on:
      - kafka
      #- xunit-tests
    command: run /scripts/LoadingTest1.js
    environment:
      KAFKA_BROKERS: "kafka:9092"

  #Data Analysis
  kafka-exporter:
    image: danielqsj/kafka-exporter
    ports:
      - "9308:9308"
    environment:
      KAFKA_BROKERS: "kafka:9092"
    depends_on:
      - kafka
      - k6-load-test


  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - kafka-exporter


  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

volumes:
  grafana-storage: